### ISSUE TITLE
Cookies are URL encoded in CookieParameters

### ISSUE THREAD

**Issue by msaindane** [Lavakumar/IronWASP#2]
The cookies are being URL encoded within the CookieParameters class. This happens when you manually use the SetCookie methods.

Cookies with the format, `CookieABC=XYZ=123&PRQ=456` get converted to `CookieABC=XYZ%3d123%26PRQ%3d456`. This would create problems in some applications as the cookie value is not valid any more.

According to the [RFC6265](http://tools.ietf.org/rfc/rfc6265.txt) the cookie-value must have the following format:

> ; US-ASCII characters excluding CTLs,
> ; whitespace DQUOTE, comma, semicolon,
> ; and backslash

**Comment by Lavakumar** [comment]
Valid issue. Fixed in version [0.9.0.1](https://github.com/Lavakumar/IronWASP/commit/f9663783a651165041ffe940f01fe4e8913b6306)
