### ISSUE TITLE
Textbox limitation in Manual Testing tab

### ISSUE THREAD

**Issue by msaindane** [Lavakumar/IronWASP#5]
Issue occurs when the POST request has a huge body (common on Multi-Part posts., e.g. uploading docs). The text box allows deleting the characters from the text, but not add to it.

Also happens in the format plugins tab under the same section, where the multi-part request is converted to XML, but I'm unable to modify the text values within the XML. I can deleted individual characters.

**Comment by Lavakumar** [comment]
Fixed
